version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: default_user
      MYSQL_PASSWORD: default_password
      MYSQL_DB: messageDB
    depends_on:
      - mysql
 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: *********
      MYSQL_USER: default_user
      MYSQL_PASSWORD: default_password
      MYSQL_DATABASE: messageDB
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:




